<?php

namespace AppBundle\Repository;

/**
 * aptekaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aptekaRepository extends \Doctrine\ORM\EntityRepository
{
}
