<?php

namespace AppBundle\Repository;

/**
 * catmcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class catmcRepository extends \Doctrine\ORM\EntityRepository
{
}
