<?php

namespace AppBundle\Repository;

/**
 * marketingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marketingRepository extends \Doctrine\ORM\EntityRepository
{
}
