<?php

namespace AppBundle\Repository;

/**
 * oborotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class oborotRepository extends \Doctrine\ORM\EntityRepository
{
}
